### ISSUE TITLE
Instantiation order errors in examples

### ISSUE THREAD

**Issue by XANOZOID** [alvarop100/Storm2#14]
Hello, all of the examples do not work for me in Pharo versions 6-8. When an example game is running through the method to initiate a scene, many of the objects in any example try to grab their image by referencing something like `game assetManager` but because they instantiate before the `addComponent` method is able to operate on them it tries to send this message to `nil`. 

I kind of see that maybe at one point it was working because each object would only have its 'instantiate` method when it hit the `on: aGame` method, but it seems like each Pharo version I tried has some 'new basicInit` trait/behavior that's appended. 

I'm currently using Ubuntu bionic beaver, tested pharo versions 6 7 and 8. Am I doing something wrong?

**Comment by apiorno** [comment]
Hello,
It should be working on Pharo 7, have you downloaded the assets?
