### ISSUE TITLE
Not clear how to run the Arkanoid game

### ISSUE THREAD

**Issue by bergel** [alvarop100/Storm2#3]
I downloaded and compiled Chipmunk. But I later realized that this is not necessary since the libs are provided in the git repo. 
I cloned the git repo in the same folder than the one that contains the images.
But apparently, the picture background.png is not found. Actually, it does not seem to be in your repo.

How can I run your game? Here is the error I obtain:
![screenshot 2017-11-09 08 45 58](https://user-images.githubusercontent.com/393742/32604032-c23255be-c52a-11e7-8d15-1123bf9e4bac.png)

**Comment by apiorno** [comment]
Hi bergel, sorry for that i had the README out of date and i did not upload files for arkanoid (i did not expect someone to use it yet).
Now the README is up to date, and files are in a folder in repo.
Chipmunk2D is disabled temporarily ( reasons are on the README file now).
Now you can start Araknoid by clonning the repo, copying the files and evaluating:
ArkanoidGame new start

**Comment by bergel** [comment]
Thanks!
I tried again, but I got an error: 'Sprite not found in RelativePath: yellow.jpeg'
yellow.png is however present. Wrong file extension?

**Comment by apiorno** [comment]
Oh Sorry, last commit was not push. Now it should work. All critics and recommendations are welcome :D

**Comment by bergel** [comment]
Okay! Works now!
But... it is extremely slow. I am on OSX. Barely playable... Is it because you are simulating the library?

**Comment by apiorno** [comment]
Surely that. I tested on Linux and had a "playable speed" , and the same as you on Windows. I Hope to be using chipmunk or another physics library again soon.

**Comment by bergel** [comment]
Let us know about your progresses. You are doing a very valuable effort

**Comment by apiorno** [comment]
Thank you :D
